version: '3'

services:
    artometrix_lab:
        tty: true
        stdin_open: true
        image: arto_labs
        restart: unless-stopped
        container_name: artometrix_labs
        command: "/bin/bash"
        build:
          dockerfile: docker/Dockerfile
          context: .
        volumes:
          - "./:/usr/code"
        ports:
          - "8087:8087"
        environment: 
           JUPYTER_TOKEN: "docker777"

